// Frame sequences generated by scripts/convert-frames.sh.
export const sequences = {
  hero: { count: 50, width: 720, height: 900 },
  m1: { count: 31, width: 720, height: 520 },
  m2: { count: 34, width: 720, height: 900 },
  final: { count: 80, width: 720, height: 900 },
} as const;

export type SequenceKey = keyof typeof sequences;

export function framePath(key: SequenceKey, index: number) {
  return `/frames/${key}/${String(index + 1).padStart(4, "0")}.webp`;
}
